# Generated by Django 5.2.12 on 2026-05-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_event_is_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
