# Generated by Django 5.2.12 on 2026-05-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_event_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(max_length=50),
        ),
    ]
