# Generated by Django 5.2.12 on 2026-05-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_ticket_qr_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="qr_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, unique=True
            ),
        ),
    ]
